# Build stage
FROM maven:3-eclipse-temurin-26-alpine AS build

WORKDIR /app

COPY backend/pom.xml .

# Download dependencies
RUN mvn dependency:go-offline -B

COPY backend/src ./src

RUN mvn clean package -DskipTests


# Run stage
FROM eclipse-temurin:17-jre-alpine

WORKDIR /app

# Install curl for Docker healthcheck and fonts for AWT
RUN apk add --no-cache curl fontconfig ttf-dejavu

COPY --from=build /app/target/*.jar app.jar

RUN mkdir -p /app/uploads && \
    chown -R nobody:nobody /app

USER nobody

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]